Para cada tabela do modelo de dados:
- Informe o objetivo da tabela (o que ela armazena)?
- Identifique a chave primária
- Identifique a(s) chave(s) estrangeira(s)

Quantas chaves primárias uma tabela pode possuir?

Quantas chaves estrangeiras uma tabela pode possuir?

Existe alguma tabela em nosso modelo com chave primária composta?

Identifique a cardinalidade entre as tabelas PRODUTO e LINHA.

Identifique a cardinalidade entre as tabelas VENDEDOR e EQUIPE.


/*
BETWEEN
IN
LIKE
OR
AND
=
<>
%
ORDER BY 
CASE
LEN
SUBSTRING
SQRT
CHAR
CHARINDEX
FLOOR
CEILING
REVERSE
*/



--SELECIONE TODOS OS VENDEDORES DA EMPRESA
SELECT * FROM VENDEDOR;

--SELECIONE O NOME DE TODOS OS VENDEDORES DA EMPRESA
SELECT NOME FROM VENDEDOR;

--SELECIONE O NOME E O CÓDIGO DA EQUIPE DO VENDEDOR DE CÓDIGO 109
SELECT NOME, CD_EQUIPE FROM VENDEDOR WHERE CD_VEND = '109'

--SELECIONE O NOME E O CÓDIGO DA EQUIPE DE TODOS OS VENDEDORES DA EQUIPE 1
SELECT NOME, CD_EQUIPE FROM VENDEDOR WHERE CD_EQUIPE = 1;

--SELECIONE O NOME E O CÓDIGO DA EQUIPE DE TODOS OS VENDEDORES QUE NÃO PERTENCEM À AQUIPE 1
SELECT NOME, CD_EQUIPE FROM VENDEDOR WHERE CD_EQUIPE <> 1;

--SELECIONE OS CLIENTES QUE POSSUEM CÓDIGO ENTRE 10 30
SELECT * FROM CLIENTE WHERE CD_CLIEN BETWEEN 10 AND 30

--SELECIONE OS CLIENTES QUE NÃO POSSUEM CÓDIGO ENTRE 10 E 30
SELECT * FROM CLIENTE WHERE CD_CLIEN NOT BETWEEN 10 AND 30

--SELECIONE OS CLIENTES QUE POSSUEM OS CÓDIGOS DE CLIENTE 12, 20, 30.
SELECT * FROM CLIENTE WHERE CD_CLIEN IN (12,20,30)

--SELECIONE TODOS OS CLIENTES QUE NÃO SEJAM DE SP NEM DE SC
SELECT * FROM CLIENTE WHERE UF NOT IN ('SP', 'SC')

--SELECIONE O NOME DE TODOS OS VENDEDORES CUJO NOME COMEÇA COM A LETRA S
SELECT NOME FROM VENDEDOR WHERE NOME LIKE 'S%';

--SELECIONE TODOS OS CLIENTES QUE NÃO SEJAM DE SP E NEM DE SC, ATIVOS, PESSOA JURÍDICA, E QUE O NOME COMEÇE COM A PALAVRA "ALB"
SELECT * FROM CLIENTE WHERE UF NOT IN ('SP', 'SC') AND ATIVO = 1 AND TP_PES = 'J' AND NOME LIKE 'ALB%'

--SELECIONE O NOME E O CÓDIGO DA EQUIPE DE TODOS OS VENDEDORES CUJO NOME COMEÇA COM A LETRA S E O CÓDIGO DA
--EQUIPE NÃO SEJA IGUAL A 1
SELECT NOME, CD_EQUIPE FROM VENDEDOR WHERE NOME LIKE 'S%' AND CD_EQUIPE <> 1;

--SELECIONE O NOME DE TODOS OS CLIENTES INATIVOS 
SELECT NOME FROM CLIENTE WHERE ATIVO = 0;

--UM CLIENTE CHAMADO "DIONISIO MEDINA" LIGOU PARA O DEPARTAMENTO DE VENDAS DA EMPRESA E REPORTOU QUE
--NÃO CONSEGUE COMPRAR PRODUTOS PELO SITE DA EMPRESA. O DEPARTAMENTO DE VENDAS SUSPEITA QUE SEJA UM 
--PROBLEMA DE SISTEMA, E PASSOU O CASO PARA VOCÊ.
--OS PRÉ-REQUISITOS DE CADASTRO PARA QUE UM CLIENTE POSSA FAZER COMPRAS PELA INTERNET SÃO: 1) DEVE POSSUIR UF CADASTRADO 2)DEVE SER UM CLIENTE ATIVO. 
--O CLIENTE ESTÁ NA LINHA COM O PESSOAL DE VENDAS ESPERANDO A SOLUÇÃO DO PROBLEMA, A BOLA ESTÁ COM VOCÊ! VEJA SE REALMENTE É UM PROBLEMA DE SISTEMA
--E INFORME O PESSOAL DE VENDAS.

SELECT ATIVO FROM CLIENTE WHERE NOME = 'DIONISIO MEDINA';



--SELECIONE O NOME DE TODOS OS CLIENTES ATIVOS DO ESTADO DE SÃO PAULO
SELECT NOME FROM CLIENTE WHERE UF = 'SP' AND ATIVO = 1;

--SELECIONE O NOME DE TODAS AS CIDADES CUJO NOME POSSUI A LETRA "E" NA SEGUNDA POSIÇÃO DE SEU NOME
SELECT CIDADE FROM CLIENTE WHERE CIDADE LIKE '_E%';

--SELECIONE O NOME DE TODAS AS CIDADES CUJO NOME POSSUI A LETRA "E" NA SEGUNDA POSIÇÃO DE SEU NOME E A 
--LETRA "A" NA ÚLTIMA POSIÇÃO DE SEU NOME
SELECT CIDADE FROM CLIENTE WHERE CIDADE LIKE '_E%';

--SELECIONE O NOME DE TODOS OS CLIENTES CUJA PENÚLTIMA LETRA DO NOME SEJA "J"
SELECT NOME FROM CLIENTE WHERE NOME LIKE '%J_';

--SELECIONE A DESCRIÇÃO DE TODAS AS EQUIPES DE VENDEDOR
SELECT DESCRICAO FROM EQUIPE;

--O GERENTE DE MARKETING ESTÁ ATUALIZANDO O PORTFÓLIO DE PRODUTOS DA EMPRESA. ELE NECESSITA DE UMA LISTA DE
--PRODUTOS ATIVOS ATUALIZADA PARA INICIAR O TRABALHO. BUSQUE A DESCRIÇÃO DE TODOS OS PRODUTOS ATIVOS DA 
--EMPRESA
SELECT DESCRICAO FROM PRODUTO WHERE ATIVO = 1;

--SELECIONE TODOS OS PRODUTOS DA LINHA DE CÓDIGO "AZE4"
SELECT * FROM PRODUTO WHERE CD_LINHA = 'AZE4';

--SELECIONE TODOS OS PRODUTOS INATIVOS DA LINHA DE CÓDIGO "AZE4" 
SELECT * FROM PRODUTO WHERE CD_LINHA = 'AZE4' AND ATIVO = 0;

--SELECIONE O CÓDIGO E A DESCRICAO DE TODAS AS LINHAS DE PRODUTO
SELECT CD_LINHA, DESCRICAO FROM LINHA;

--SELECIONE A DESCRICAO DE TODAS AS UNIDADES TRABALHADAS PELA EMPRESA
SELECT DESCRICAO FROM UNIDADE;

--SELECIONE A DESCRIÇÃO DA UNIDADE DE CÓDIGO "PT" OU "KG"
SELECT DESCRICAO FROM UNIDADE WHERE UNIDADE = 'PT' OR UNIDADE = 'KG';

--SELECIONE TODAS AS NOTAS FISCAIS DO CLIENTE DE CÓDIGO "21388"
SELECT * FROM NOTA WHERE CD_CLIEN = 21388;

--SELECIONE TODAS AS NOTAS FISCAIS DO VENDEDOR DE CÓDIGO "54"
SELECT * FROM NOTA WHERE CD_VEND = '54';

--SELECIONE TODAS AS NOTAS FISCAIS COM VALOR ACIMA DE R$1000, 00
SELECT * FROM NOTA WHERE VL_TOTAL > 1000;

--SELECIONE TODAS AS NOTAS FISCAIS COM VALOR ENTRE R$100, 00 E R$150, 00
SELECT * FROM NOTA WHERE VL_TOTAL >= 100 AND VL_TOTAL <= 150;

--SELECIONE TODAS AS NOTAS FISCAIS COM VALOR ENTRE R$100, 00 E R$150, 00 DO CLIENTE DE CÓDIGO 21772
SELECT * FROM NOTA WHERE VL_TOTAL >= 100 AND VL_TOTAL <= 150 AND CD_CLIEN = 21772;

--QUANTAS UNIDADES DO PRODUTO DE CÓDIGO "1083" CABEM EM UMA CAIXA? MONTE O COMANDO SELECT.
SELECT * FROM UNID_PROD WHERE CD_PROD = 1083 AND UNIDADE = 'CX';

--SELECIONE O TELEFONE DE FAX (TP_TEL = 'FX') DO CLIENTE DE CÓDIGO 1
SELECT NUMERO FROM TELEFONE WHERE CD_CLIEN = 1 AND TP_TEL = 'FX';

--SELECIONE O TELEFONE COMERCIAL (TP_TEL = 'CO') DO CLIENTE DE CÓDIGO 1
SELECT NUMERO FROM TELEFONE WHERE CD_CLIEN = 1 AND TP_TEL = 'CO';

--SELECIONE O TELEFONE DE RECADO (TP_TEL = 'RE') DO CLIENTE DE CÓDIGO 5276
SELECT NUMERO FROM TELEFONE WHERE CD_CLIEN = 5276 AND TP_TEL = 'RE';

--SELECIONE O TELEFONE CELULAR (TP_TEL = 'CE') DO CLIENTE DE CÓDIGO 5276
SELECT NUMERO FROM TELEFONE WHERE CD_CLIEN = 5276 AND TP_TEL = 'CE';

--SELECIONE O CÓDIGO DO PRODUTO E A DESCRIÇÃO DO PRODUTO DE TODOS OS PRODUTOS QUE POSSUEM CÓDIGO DE NÚMERO PAR
SELECT CD_PROD, DESCRICAO FROM PRODUTO WHERE CD_PROD%2 = 0

--SELECIONE O NÚMERO E O TIPO DE TELEFONE DE TODOS OS TELEFONES DO CLIENTE DE CÓDIGO 5276
SELECT TP_TEL, NUMERO FROM TELEFONE WHERE  CD_CLIEN = 5276;

--SELECIONE O NOME DOS VENDEDORES EM ORDEM ALFABÉTICA (ORDEM CRESCENTE)
SELECT NOME FROM VENDEDOR ORDER BY NOME;

--SELECIONE O TIPO DE PESSOA E O NOME DE TODOS OS CLIENTES ATIVOS DE SP. ORDENE O RESULTADO POR TIPO DE PESSOA
--E POR NOME (ORDEM CRESCENTE)
SELECT TP_PES, NOME FROM CLIENTE WHERE ATIVO = 1 AND UF = 'SP' ORDER BY TP_PES, NOME;

--SELECIONE OS ESTADOS DISTINTOS DOS CLIENTES
SELECT DISTINCT UF FROM CLIENTE

--SELECT - INTO => NOSSO MODELO DE DADOS NÃO POSSUI UMA TABELA DE ESTADO. O ADMINISTRADOR DE DADOS RESOLVEU CRIAR ESTA TABELA E TE PASSOU A TAREFA.
--A COLUNA UF DA TABELA DE CLIENTES POSSUI TODOS OS ESTADOS DOS CLIENTES. SELECIONE OS ESTADOS DISTINTOS E GRAVE-OS EM UMA NOVA TABELA CHAMADA
--TB_ESTADO
SELECT DISTINCT UF INTO #TESTE FROM CLIENTE

--O SETOR DE MARKETING DA EMPRESA NECESSITA DE UMA RELAÇÃO DE CLIENTES, ATIVOS E INATIVOS, DO ESTADO DE SÃO PAULO. VOCÊ DEVE SELECI0NAR O ESTADO E
--A INFORMAÇÃO DE ATIVO OU INATIVO. PARA DEIXAR O RESULTADO MAIS LEGÍVEL, VOCÊ DEVE USAR A SEGUINTE REGRA PARA TRANSFORMAR O CAMPO ATIVO:
--QUANDO ATIVO = 0 ENTÃO MOSTRAR "INATIVO", QUANDO ATIVO = 1 ENTÃO MOSTRAR "ATIVO". O NOME DESTA COLUNA DE SER "STATUS"
SELECT	UF,
		CASE
			WHEN ATIVO = 1 THEN 'ATIVO'
			ELSE 'INATIVO'
		END AS STATUS
FROM	CLIENTE
WHERE	UF = 'SP'

--SELECIONE A DESCRIÇÃO DA LINHA DO PRODUTO E QUANTIDADE DE CARACTERES QUE A DESCRIÇÃO DA LINHA POSSUI.
--DEPOIS RESPONDA: QUAL DESCRICAO DE LINHA POSSUI O MENOR TAMANHO (MENOR QUANTIDADE DE CARACTERES)?
SELECT DESCRICAO, LEN (DESCRICAO) FROM LINHA

--DESAFIO: FAÇA O MESMO EXERCÍCIO ANTERIOR, PORÉM APLICADO NA TABELA DE CLIENTES. OU SEJA, SELECIONE O NOME E O TAMANHO DO NOME DE TODOS OS CLIENTES.
--DEPOIS RESPONDA: QUAL NOMDE DE CLIENTE POSSUI O MENOR TAMANHO (MENOR QUANTIDADE DE CARACTERES)?
--QUE CLÁUSULA DO SELECT PODE DE AJUDAR A REALIZAR ESTA TAREFA?

SELECT NOME, LEN (NOME) FROM CLIENTE ORDER BY LEN (NOME)

--SELECIONE AS QUATRO PRIMEIRAS LETRAS DA DESCRICAO DAS LINHAS DE PRODUTOS.
SELECT LEFT (DESCRICAO, 4) FROM LINHA

--SELECIONE AS QUATRO ÚLTIMAS LETRAS DA DESCRICAO DAS LINHAS DE PRODUTOS.
SELECT RIGHT (DESCRICAO, 4) FROM LINHA

--SELECIONE A SEGUNDA E A TERCEIRA LETRA DA DESCRICAO DAS LINHAS DE PRODUTOS
SELECT SUBSTRING (DESCRICAO, 2,2) FROM LINHA

--SELECIONE A RAIZ QUADRADA DE 9
SELECT SQRT(9)

--SELECIONE A RAIZ QUADRADA DE 12, ARREDONDADA EM DUAS CASAS DECIMAIS
SELECT ROUND (SQRT(12), 2)

--SELECIONE A RAIZ QUADRADA DE 12, ARREDONDADA NO PRÓXIMO NÚMERO INTEIRO
SELECT CEILING (SQRT(12))

--SELECIONE A RAIZ QUADRADA DE 12, ARREDONDADA NO NÚMERO INTEIRO ANTERIOR
SELECT FLOOR (SQRT(12))

--DESAFIO: EXISTEM VÁRIAS FORMAS DE CRIPTOGRAFAR DADOS. ABAIXO FOI UTILIZADA UMA LÓGICA QUALQUER PARA CRIPTOGRAFAR UMA FRASE.
--CADA NÚMERO (SEPARADOS POR "-"), REPRESENTAM UM CARACTER. VOCÊ CONSEGUE DESCOBRIR A CHAVE DE CRIPTOGRAFIA PARA DECRIPTOGRAFAR A FRASE E 
--VERIFICAR O QUE ESTÁ ESCRITO?
--SE ESTIVER DIFÍCIL, SOLICITE DICAS AO PROFESSOR!

70 - 85 - 78 - 67 - 79 - 69 - 83 - 45 - 83 - 81 - 76
SELECT CHAR (67)

--DESAFIO: O SETOR DE MARKETING RESOLVEU ENVIAR UMA MALA DIRETA PARA TODOS OS CLIENTES ATIVOS DA EMPRESA.
--PARA ENVIAR UMA CARTA PERSONALIZADA, O PESSOAL DE MARKETING DESEJA RECEBER UMA LISTA COM O PRIMEIRO NOME DE TODOS OS CLIENTES ATIVOS.
--EXEMPLO: "WESLLEY MOURA". NA SUA LISTA DEVE CONSTAR APENAS "WESLLEY"
--USE A FUNÇÃO CHARINDEX E SUBSTRING PARA RESOLVER O PROBLEMA.
 
SELECT NOME, SUBSTRING (NOME, 1, CHARINDEX (' ', NOME)) FROM CLIENTE

--DESAFIO FINAL!!!
--CONSTANTEMENTE O PROGRAMARDOR OU O DBA PRECISAM RESOLVER PROBLEMAS QUE ENVOLVEM TANTO CONHECIMENTO DE LÓGICA QUANTO CONHECIMENTO NA TECNOLOGIA
--QUE ESTÁ TRABALHANDO. AGORA VAMOS TESTAR SUA LÓGICA!
--UTILIZANDO OS COMANDOS QUE VOCÊ APRENDEU HOJE, ESCREVA UM COMANDO SQL QUE RETORNE O ÚLTIMO NOME DE CADA CLIENTE.
--CONCENTRE-SE, PENSE, TESTE...IMAGINE QUE ESTÁ NO SEU TRABALHO.

SELECT REVERSE (SUBSTRING (REVERSE('WESLLEY GOMES MOURA'), 1, CHARINDEX (' ', REVERSE ('WESLLEY GOMES MOURA'))))