--SELECIONE O NOME E A EQUIPE DE TODOS OS VENDEDORES

--SELECIONE O NOME E TODOS OS TELEFONES DO CLIENTE DE CÓDIGO 1

--SELECIONE O NOME E O NÚMERO DE FAX (TP_TEL = FX) DE TODOS OS CLIENTES QUE MORAM EM SÃO PAULO (UF = SP)

--SELECIONE A DESCRIÇÃO DO PRODUTO E A DESCRIÇÃO DE SUA LINHA

--SELECIONE A DESCRICAO DO PRODUTO, A DESCRICAO UNIDADE, E O FATOR DE TODOS OS PRODUTOS

--SELECIONE A DESCRICAO DO PRODUTO, A DESCRICAO UNIDADE, E O FATOR DO PRODUTO DE CÓDIGO 1083

--SELECIONE A DESCRICAO DO PRODUTO, A DESCRICAO DA LINHA, A DESCRICAO UNIDADE E O FATOR DO PRODUTO DE CÓDIGO 1083

--SELECIONE A DESCRICAO DO PRODUTO, A DESCRICAO DA LINHA, A DESCRICAO UNIDADE E O FATOR DE TODOS OS PRODUTOS ATIVOS

--SELECIONE O NÚMERO DA NOTA FISCAL, O VALOR TOTAL DA NOTA FISCAL, O NOME DO VENDEDOR QUE EFETIVOU A VENDA E A DESCRICAO DA EQUIPE QUE ELE PERTENCE

--SELECIONE O NÚMERO DA NOTA FISCAL, O VALOR TOTAL DA NOTA FISCAL, O NOME DO CLIENTE QUE EFETUOU A COMPRA E OS TELEFONES DESSE CLIENTE

--SELECIONE O NÚMERO DA NOTA FISCAL, O VALOR TOTAL DA NOTA FISCAL, O NOME DO CLIENTE QUE EFETUOU A COMPRA E O TELEFONE DE FAX (TP_TEL = 'FX') DESSE CLIENTE. FAÇA UMA RESTRIÇÃO PELO NÚMERO DA NOTA IGUAL A 284564

--SELECIONE O NÚMERO DA NOTA, A DESCRIÇÃO DOS PRODUTOS VENDIDOS NA NOTA E A DESCRIÇÃO DA LINHA DESSES PRODUTOS

--SELECIONE O NÚMERO DA NOTA, A DESCRIÇÃO DOS PRODUTOS VENDIDOS NA NOTA E A DESCRIÇÃO DA LINHA DESSES PRODUTOS. FAÇA UMA RESTRIÇÃO PELO NÚMERO DA NOTA IGUAL A 284564

--SELECIONE O NÚMERO DA NOTA FISCAL, O NOME DO CLIENTE QUE EFETUOU A COMPRA E SEUS TELEFONES DE FAX SOMENTE DOS CLIENTES QUE MORAM EM 'SP'

--SELECIONE O NÚMERO DA NOTA FISCAL, O NOME DO CLIENTE QUE EFETUOU A COMPRA E SEUS TELEFONES DE FAX SOMENTE DOS CLIENTES QUE MORAM EM 'SP' E QUE SÃO PESSOA FÍSICA (TP_PES = 'F')

--SELECIONE O NÚMERO DA NOTA FISCAL, O NOME DO CLIENTE QUE EFETUOU A COMPRA E SEUS TELEFONES DE FAX SOMENTE DOS CLIENTES QUE MORAM EM 'SP', QUE SÃO PESSOA FÍSICA (TP_PES = 'J') E QUE ESTÃO ATIVOS

