/*****************************************************************************************
TOP
*****************************************************************************************/

--SELECIONE O NOME DOS 10 PRIMEIROS CLIENTES ATIVOS. ORDENE O RESULTADO PELO NOME DO CLIENTE.

--SELECIONE O CÓDIGO E O NOME DOS 10 PRIMEIROS CLIENTES ATIVOS QUE MORAM EM 'SP'. ORDENE O RESULTADO PELO CÓDIGO DO CLIENTE.

--SELECIONE NOME DOS 7 PRIMEIROS CLIENTES ATIVOS QUE MORAM EM 'SC'. ORDENE O RESULTADO PELO NOME DO CLIENTE.

--SELECIONE NOME DOS 7 PRIMEIROS CLIENTES ATIVOS QUE MORAM EM 'SC'. ORDENE O RESULTADO PELO NOME DO CLIENTE.

--SELECIONE O NOME DO VENDEDOR E A DESCRIÇÃO DA EQUIPE DOS 20 PRIMEIROS VENDEDORES QUE PERTENCEM A EQUIPE DE CÓDIGO 1. ORDENE O RESULTADO PELO NOME DO VENDEDOR.

--SELECIONE O NOME DO VENDEDOR E A DESCRIÇÃO DA EQUIPE DOS 20 PRIMEIROS VENDEDORES QUE PERTENCEM A EQUIPE DE CÓDIGO 1. ORDENE O RESULTADO PELO NOME DO VENDEDOR.

--SELECIONE A DESCRICAO DO PRODUTO E A DESCRIÇÃO DA LINHA DOS 15 PRIMEIROS PRODUTOS QUE PERTENCEM A LINHA DE CÓDIGO = 'ACMV'

--DESAFIO: SELECIONE A DESCRIÇÃO DO PRODUTO E A DESCRICAO DA LINHA DOS 10 PRODUTOS MAIS VENDIDOS 

--DESAFIO: SELECIONE A DESCRIÇÃO DO PRODUTO E A DESCRICAO DA LINHA DOS 10 PRODUTOS MENOS VENDIDOS

--DESAFIO: SELECIONE O NOME E O VALOR TOTAL DE VENDAS DOS 10 PRIMEIROS CLIENTES QUE MAIS REALIZAM COMPRAS