/*
PROGRAMAÇÃO AVANÇADA
AGORA VAMOS COMEÇAR A FAZER QUERIES QUE FAZEM SENTIDO AO NEGÓCIO DA NOSSA EMPRESA.

UTILIZAREMOS OS ALGORITMOS DE JUNÇÃO DE TABELAS QUE JÁ CONHECEMOS, RESTRIÇÕES EM COLUNAS, RESTRIÇÕES EM DADOS AGRUPADOS
E SUB SELECTs.

O NÍVEL DE COMPLEXIDADE DE NOSSAS QUERIES VAI AUMENTAR MUITO. PORTANTO NÃO PASSE ADIANTE SE NÃO ENTENDER O EXERCÍCIO.
VAMOS LÁ!
*/

CREATE TABLE FUNCIONARIO 
(
	COD_FUNC	INT,
	NOME		VARCHAR(100),
	COD_GERENTE INT
)
GO

INSERT INTO FUNCIONARIO VALUES (1, 'WESLLEY', 2)
INSERT INTO FUNCIONARIO VALUES (2, 'KEILA', 3)
INSERT INTO FUNCIONARIO VALUES (3, 'JULIA', 4)
INSERT INTO FUNCIONARIO VALUES (4, 'JOSE', 5)
INSERT INTO FUNCIONARIO VALUES (5, 'MARIA', NULL)
GO

--SELECIONE O NOME DO FUNCIONÁRIO E O NOME DE SEU GERENTE
SELECT	F.COD_FUNC,
		F.NOME AS NOME_FUNC,
		G.NOME AS NOME_GERENTE
FROM	FUNCIONARIO F
		LEFT JOIN FUNCIONARIO G
		ON F.COD_GERENTE = G.COD_FUNC	

--SELECIONE A QUANTIDADE TOTAL DE TODAS AS VENDAS

--SELECIONE O VALOR TOTAL DE TODAS AS VENDAS

--SELECIONE A MÉDIA DE TODAS AS VENDAS

--SELECIONE O VALOR DA MENOR VENDA JÁ REALIZA NA HISTÓRIA DA EMPRESA

--SELECIONE O VALOR DA MAIOR VENDA JA REALIZADA NA HISTÓRIA DA EMPRESA

--SELECIONE A DESCRICAO DA EQUIPE E A QUANTIDADE DE VENDEDORES PERTENCENTES A CADA EQUIPE.
--RESTRIÇÕES: A DESCRICAO DA EQUIPE DEVE CONTER A LETRA "E" E A EQUIPE DEVE POSSUIR NO MÁXIMO 10 VENDEDORES
SELECT	E.DESCRICAO,
		COUNT (*)
FROM	VENDEDOR V
		JOIN EQUIPE E
		ON V.CD_EQUIPE = E.CD_EQUIPE
WHERE	E.DESCRICAO LIKE '%E%'
GROUP BY
		E.DESCRICAO
HAVING COUNT (*) <= 10

--SELECIONE O VALOR TOTAL DE VENDAS POR ESTADO.
--RESTRIÇÕES:	O VALOR TOTAL DE VENDAS NÃO PODE SER MAIOR QUE 300.000
--				CONTABILIZE APENAS VENDAS DE CLIENTES ATIVOS
SELECT	C.UF,
		SUM (N.VL_TOTAL)
FROM	NOTA N
		JOIN CLIENTE C
		ON N.CD_CLIEN = C.CD_CLIEN
WHERE	C.ATIVO = 1
GROUP BY C.UF
HAVING SUM (N.VL_TOTAL) <= 300000

--SELECIONE O NOME DO VENDEDOR, O VALOR TOTAL DE VENDAS E A MÉDIA DE VENDAS DE CADA VENDEDOR
SELECT	V.NOME,
		SUM (N.VL_TOTAL),
		AVG(N.VL_TOTAL)
FROM	NOTA N
		JOIN VENDEDOR V
		ON N.CD_VEND = V.CD_VEND
GROUP BY 
		V.NOME

--SELECIONE O NOME DO VENDEDOR E O VALOR TOTAL DE VENDAS DE CADA VENDEDOR.
--RESTRIÇÕES: O VALOR TOTAL DE VENDAS DO VENDEDOR DEVE SER MAIOR QUE A MÉDIA DE TODAS AS VENDAS JÁ REGISTRADAS
SELECT	V.NOME,
		SUM (N.VL_TOTAL)
FROM	NOTA N
		JOIN VENDEDOR V
		ON N.CD_VEND = V.CD_VEND
GROUP BY 
		V.NOME
HAVING SUM (N.VL_TOTAL) >= (SELECT AVG(N.VL_TOTAL) FROM NOTA N)

--DESAFIO - RELATÓRIO DE PERFORMANCE DE VENDAS POR VENDEDOR: O DIRETOR DA SUA EMPRESA RESOLVEU BONIFICAR OS MELHORES VENDEDORES DA EMPRESA!
--PARA ISSO, ELE PRECISA DE UM RANK DE VENDEDORES.
--			SELECIONE O NOME DO VENDEDOR, 
--			A SOMA TOTAL DE VENDAS DO VENDEDOR ,
--			A SOMA DE TODAS AS VENDAS DA EMPRESA,
--			O PERCENTUAL DE VENDA DO VENDEDOR EM RELAÇÃO AO TOTAL DE VENDAS DA EMPRESA
--ORDENE O RESULTADO PELO PERCENTUAL DE VENDA DO VENDEDOR
--COMO O DIRETOR DA EMPRESA VAI BONIFICAR APENAS OS 10 MELHORES, FAÇA A RESTRIÇÃO SOMENTE DOS TOP 10 MELHORES
--NO ENTANTO, O DIRETOR NÃO QUER BONIFICAR AQUELES VENDEDORES QUE POSSUEM PERCENTUAL DE VENDAS MENOR DE 1.5%
SELECT	TOP 10
		V.NOME,	
		SUM (N.VL_TOTAL),
		(SELECT SUM (VL_TOTAL) FROM NOTA),
		(SUM (N.VL_TOTAL) / (SELECT SUM (VL_TOTAL) FROM NOTA)) * 100 AS PERC
FROM	NOTA N
		JOIN VENDEDOR V
		ON V.CD_VEND = N.CD_VEND
GROUP BY 
		V.NOME
HAVING ((SUM (N.VL_TOTAL) / (SELECT SUM (VL_TOTAL) FROM NOTA)) * 100) > 1.5
ORDER BY PERC DESC		

--SELECIONE A DESCRICAO DA EQUIPE, A QUANTIDADE TOTAL DE NOTAS FATURADAS E A SOMA TOTAL DE NOTAS FATURADAS
--RESTRIÇÕES: BUSQUE APENAS EQUIPES QUE FATURARAM MAIS DE 1000 NOTAS OU QUE FATURARAM MAIS DE R$ 1.000.000, 00
SELECT	E.DESCRICAO,
		COUNT (*),
		SUM (N.VL_TOTAL)
FROM	NOTA N
		JOIN VENDEDOR V
			JOIN EQUIPE E
			ON V.CD_EQUIPE = E.CD_EQUIPE
		ON N.CD_VEND = V.CD_VEND
GROUP BY 
		E.DESCRICAO
HAVING COUNT (*) > 1000 OR SUM (N.VL_TOTAL) >= 1000000







--SELECIONE O NOME E O ESTADO DE TODOS OS CLIENTES QUE POSSUEM O MESMO ESTADO DO CLIENTE DE CÓDIGO 1
select NOME, UF from cliente WHERE UF = (SELECT UF FROM CLIENTE WHERE CD_CLIEN = 1)

--SELECIONE O NOME DE TODOS OS VENDEDORES QUE PERTENCEM À MESMA EQUIPE DO VENDEDOR DE CÓDIGO 10
SELECT NOME FROM VENDEDOR WHERE CD_EQUIPE = (SELECT CD_EQUIPE FROM VENDEDOR WHERE CD_VEND = '10')

--SELECIONE O TIPO DE TELEFONE E O NÚMERO DO TELEFONE DO CLIENTE DE MENOR CÓDIGO CADASTRADO NA TABELA DE CLIENTE
SELECT TP_TEL, NUMERO FROM TELEFONE WHERE CD_CLIEN = (SELECT MIN(CD_CLIEN) FROM CLIENTE)

--SELECIONE O NÚMERO DO TELEFONE DE FAX DO CLIENTE DE MENOR CÓDIGO CADASTRADO NA TABELA DE CLIENTE
SELECT TP_TEL, NUMERO FROM TELEFONE WHERE CD_CLIEN = (SELECT MIN(CD_CLIEN) FROM CLIENTE) AND TP_TEL = 'FX'

--SELECIONE A DESCRICAO DA LINHA E A DESCRICAO DO PRODUTO DE TODOS OS PRODUTOS QUE PERTENCEM À MESMA LINHA DO PRODUTO DE 
--CÓDIGO 1083
SELECT	P.DESCRICAO,
		L.DESCRICAO
FROM	PRODUTO P
		JOIN LINHA L
		ON P.CD_LINHA = L.CD_LINHA
WHERE	P.CD_LINHA = (SELECT CD_LINHA FROM PRODUTO WHERE CD_PROD = 1083)


