/*****************************************************************************************
CROSS JOIN
*****************************************************************************************/

--USANDO JOIN
SELECT	V.NOME, E.DESCRICAO
FROM	VENDEDOR V
		join EQUIPE E
		on V.CD_EQUIPE = E.CD_EQUIPE
WHERE	V.CD_VEND = '1'


--USANDO CROSS JOIN
SELECT	V.NOME, E.DESCRICAO
FROM	VENDEDOR V
		cross join EQUIPE E
WHERE	V.CD_VEND = '1'


--SELECIONE O NOME DO VENDEDOR CRUZANDO COM AS DESCRICÕES DAS EQUIPES.

--SELECIONE O NOME DO VENDEDOR CRUZANDO COM AS DESCRICÕES DAS EQUIPES. BUSCAR SOMENTE OS DADOS DO VENDEDOR DE CÓDIGO 1
 
--SELECIONE O NOME DO PRODUTO CRUZANDO COM AS DESCRICÕES DAS LINHAS.

--SELECIONE O NOME DO PRODUTO CRUZANDO COM AS DESCRICÕES DAS LINHAS. BUSCAR SOMENTE OS DADOS DO PRODUTO DE CÓDIGO 1083.