/*****************************************************************************************
AGRUPAMENTO
*****************************************************************************************/

--SELECIONE O NOME DO CLIENTE E O MENOR VALOR DE COMPRA QUE ELE JÁ FEZ  

--SELECIONE O NOME DO CLIENTE E O MAIOR VALOR DE COMPRA QUE ELE JÁ FEZ

--SELECIONE O NOME DO CLIENTE E A SOMA DE COMPRAS QUE ELE JÁ FEZ

--SELECIONE O NOME DO CLIENTE E A MEDIA DAS COMPRAS QUE ELE JÁ FEZ

--SELECIONE O NOME DO CLIENTE E A QUANTIDADE DE COMPRAS QUE ELE JÁ FEZ

--SELECIONE O NOME DO CLIENTE, O MAIOR VALOR DE COMPRA, O MENOR VALOR DE COMPRA, A SOMA DE TODAS AS COMPRAS, A MÉDIA DE COMPRAS E A QUANTIDADE DE COMPRAS QUE O CLIENTE JÁ REALIZOU.

--SELECIONE O NOME DO CLIENTE E O MAIOR VALOR DE COMPRA QUE ELE JÁ FEZ. BUSQUE SOMENTE OS DADOS DO CLIENTE DE CÓDIGO = 21388

--SELECIONE O NOME DO CLIENTE E O MAIOR VALOR DE COMPRA QUE ELE JÁ FEZ. BUSQUE SOMENTE OS DADOS DO CLIENTE DE CÓDIGO = 21388

--SELECIONE O NOME DO CLIENTE E A SOMA DE COMPRAS QUE ELE JÁ FEZ. BUSQUE SOMENTE OS DADOS DO CLIENTE DE CÓDIGO = 21388

--SELECIONE O NOME DO CLIENTE E A MEDIA DAS COMPRAS QUE ELE JÁ FEZ. BUSQUE SOMENTE OS DADOS DO CLIENTE DE CÓDIGO = 21388

--SELECIONE O NOME DO CLIENTE E A QUANTIDADE DE COMPRAS QUE ELE JÁ FEZ.  BUSQUE SOMENTE OS DADOS DO CLIENTE DE CÓDIGO = 21388

--SELECIONE O NOME DO CLIENTE, O MAIOR VALOR DE COMPRA, O MENOR VALOR DE COMPRA, A SOMA DE TODAS AS COMPRAS, A MÉDIA DE COMPRAS E A QUANTIDADE DE COMPRAS QUE O CLIENTE JÁ REALIZOU.

--SELECIONE O NOME DO CLIENTE, O MAIOR VALOR DE COMPRA, O MENOR VALOR DE COMPRA, A SOMA DE TODAS AS COMPRAS, A MÉDIA DE COMPRAS E A QUANTIDADE DE COMPRAS QUE O CLIENTE JÁ REALIZOU. 
--BUSQUE SOMENTE OS DADOS DO CLIENTE DE CÓDIGO = 21388

--SELECIONE A MÉDIA DE VENDA FEITA PARA SÃO PAULO (SP)

--SELECIONE A SOMA DE VENDA FEITA PARA O RIO DE JANEIRO (RJ)

--SELECIONE A QUANTIDADE DE VENDA FEITA PARA SANTA CATARINA (SC)

--SELECIONE A DESCRIÇÃO DO PRODUTO E A SOMA DE TODAS AS VENDAS JÁ REALIZADAS DESTE PRODUTO

--SELECIONE A DESCRIÇÃO DO PRODUTO, A DESCRIÇÃO DA LINHA, E A MÉDIA DE TODAS AS VENDAS JÁ REALIZADAS DESTE PRODUTO

--RELATÓRIO DE VENDAS POR LINHA DE PRODUTO
--SELECIONE A DESCRIÇÃO DA LINHA E A SOMA DE TODAS AS VENDAS DESTA LINHA