/*
AVALIAÇÃO SQL
DICA: TODOS OS EXERCÍCIOS JÁ FORAM FEITOS EM SALA DE AULA.
NÃO SE PREOCUPE QUE NÃO EXISTE NENHUMA "PEGADINHA", APENAS LEMBRE-SE DE COMO FIZEMOS EM SALA QUE NÃO TERÁ PROBLEMAS.
USE O MER QUANDO NECESSÁRIO.

BOA SORTE ANALISTAS!!!
*/

--1) SELECIONE TODOS OS VENDEDORES DA EMPRESA


--2) SELECIONE O NOME DE TODOS OS VENDEDORES DA EMPRESA


--3) SELECIONE O NOME E O CÓDIGO DA EQUIPE DO VENDEDOR DE CÓDIGO 109


--4) SELECIONE O NOME E O CÓDIGO DA EQUIPE DE TODOS OS VENDEDORES DA EQUIPE 1


--5) SELECIONE O NOME E O CÓDIGO DA EQUIPE DE TODOS OS VENDEDORES QUE NÃO PERTENCEM À AQUIPE 1


--6) SELECIONE OS CLIENTES QUE POSSUEM CÓDIGO ENTRE 10 30


--7) SELECIONE OS CLIENTES QUE NÃO POSSUEM CÓDIGO ENTRE 10 E 30


--8) SELECIONE OS CLIENTES QUE POSSUEM OS CÓDIGOS DE CLIENTE 12, 20, 30.


--9) SELECIONE TODOS OS CLIENTES QUE NÃO SEJAM DE SP NEM DE SC


--10) SELECIONE O NOME DE TODOS OS VENDEDORES CUJO NOME COMEÇA COM A LETRA S


--11) SELECIONE TODOS OS CLIENTES QUE NÃO SEJAM DE SP E NEM DE SC, ATIVOS, PESSOA JURÍDICA, E QUE O NOME COMEÇE COM A PALAVRA "ALB"


--12) O GERENTE DE MARKETING ESTÁ ATUALIZANDO O PORTFÓLIO DE PRODUTOS DA EMPRESA. ELE NECESSITA DE UMA LISTA DE
--PRODUTOS ATIVOS ATUALIZADA PARA INICIAR O TRABALHO. BUSQUE A DESCRIÇÃO DE TODOS OS PRODUTOS ATIVOS DA 
--EMPRESA


--13) SELECIONE O CÓDIGO E A DESCRICAO DE TODAS AS LINHAS DE PRODUTO


--14) SELECIONE A DESCRICAO DE TODAS AS UNIDADES TRABALHADAS PELA EMPRESA


--15) SELECIONE A DESCRIÇÃO DA UNIDADE DE CÓDIGO "PT" OU "KG"


--16) SELECIONE TODAS AS NOTAS FISCAIS DO CLIENTE DE CÓDIGO "21388"


--17) SELECIONE TODAS AS NOTAS FISCAIS DO VENDEDOR DE CÓDIGO "54"


--18) SELECIONE TODAS AS NOTAS FISCAIS COM VALOR ACIMA DE R$1000, 00


--19) SELECIONE TODAS AS NOTAS FISCAIS COM VALOR ENTRE R$100, 00 E R$150, 00


--20) SELECIONE O NOME DOS VENDEDORES EM ORDEM ALFABÉTICA (ORDEM CRESCENTE)


--SELECIONE O NOME DO VENDEDOR E A DESCRIÇÃO DE SUA EQUIPE

--21) SELECIONE O NOME DO VENDEDOR E A DESCRIÇÃO DE SUA EQUIPE DE TODOS OS VENDEDORES QUE PERTENCEM À EQUIPE DE DESCRIÇÃO "KEY-ACCOUNT"

--22) SELECIONE A DESCRIÇÃO DA EQUIPE E A QUANTIDADE DE VENDEDORES DE CADA EQUIPE


--23) SELECIONE O NOME DO CLIENTE E A SOMA DE TODAS AS VENDAS DO CLIENTE DE CÓDIGO 45



--24) SELECIONE O NOME DO CLIENTE, SOMA DE TODAS SUAS VENDAS, A MENOR COMPRA, A MAIOR COMPRA, A MÉDIA DE COMPRAS 
--E A QUANTIDADE TOTAL DE COMPRAS DO CLIENTE DE CÓDIGO 45
--(ANALISE O RESULTADO E VEJA SE FAZ SENTIDO. DEPOIS NAVEGUE NA TABELA DE NOTAS RESTRINGINDO PELO CÓDIGO DO CLIENTE PARA ENTENDER MELHOR O RESULTADO DA SUA QUERY)



--25) SELECIONE O NOME DO VENDEDOR E O VALOR TOTAL DE VENDAS DE CADA VENDEDOR.
--RESTRIÇÕES: O VALOR TOTAL DE VENDAS DO VENDEDOR DEVE SER MAIOR QUE A MÉDIA DE TODAS AS VENDAS JÁ REGISTRADAS



--26) RELATÓRIO DE PERFORMANCE DE VENDAS POR VENDEDOR: O DIRETOR DA SUA EMPRESA RESOLVEU BONIFICAR OS MELHORES VENDEDORES DA EMPRESA!
--PARA ISSO, ELE PRECISA DE UM RANK DE VENDEDORES.
--SELECIONE O NOME DO VENDEDOR, 
--			A SOMA TOTAL DE VENDAS DO VENDEDOR ,
--			A SOMA DE TODAS AS VENDAS DA EMPRESA,
--			O PERCENTUAL DE VENDA DO VENDEDOR EM RELAÇÃO AO TOTAL DE VENDAS DA EMPRESA
--ORDENE O RESULTADO PELO PERCENTUAL DE VENDA DO VENDEDOR
--COMO O DIRETOR DA EMPRESA VAI BONIFICAR APENAS OS 10 MELHORES, FAÇA A RESTRIÇÃO SOMENTE DOS TOP 10 MELHORES
--NO ENTANTO, O DIRETOR NÃO QUER BONIFICAR AQUELES VENDEDORES QUE POSSUEM PERCENTUAL DE VENDAS MENOR DE 1.5%




